/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Babysitter {

    /*
    Variable declaration
     */
    int pay;
    int start;
    int end;
    char family;
    boolean busy;

    /*
    Constructor(s)
     */
    Babysitter() {
        this.pay = 0;
        this.busy = false;
    }

    /*
    Functions
     */
    void setJob() {

    }

    void calculatePay() {

    }

    int getPay() {
        return this.pay;
    }

    boolean isBusy() {
        return this.busy;
    }
}
